# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos64_ja"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/3657281/centos64_ja.box"

  if defined? VagrantPlugins::HostManager
    config.hostmanager.enabled = false
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  config.ssh.forward_agent = true

  config.vm.define :vagrantweb do |web|
    web.vm.network :private_network, ip: "192.168.33.106"
    web.vm.hostname = 'vagrant.alermo.com'
    web.vm.synced_folder "../", "/var/www/html", :create => true, :owner=> 'vagrant', :group=>'vagrant', :mount_options => ['dmode=777,fmode=755']
    web.vm.provider :virtualbox do |vb|
      #vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    web.vm.provision :chef_solo do |chef|
      chef.add_recipe "base"
      chef.add_recipe "php-mysql-httpd"
      chef.add_recipe "alermo"
      chef.add_recipe "composer"
      chef.json = {
        :composer => {
          :install_path => "/usr/local/bin"
        }
      }
    end
  end

end