<?php

return array (
    'site'         => array(
        1               => 'yshop',
        2               => 'zozo',
        4               => 'amazon',
        5               => 'felissimo',
        6               => 'locondo',
        7               => 'fashionwalker',
        8               => 'dinos',
        9               => 'nissen',
        10              => 'bellemaison',
        11              => 'magaseek',
        12              => 'stylife',
		13 	=> 'buyma'
    ),
    'shop_id'      => array(
        'yshop'         => 1,
        'zozo'          => 2,
        'amazon'        => 4,
        'felissimo'     => 5,
        'locondo'       => 6,
        'fashionwalker' => 7,
        'dinos'         => 8,
        'nissen'        => 9,
        'bellemaison'   => 10,
        'magaseek'      => 11,
        'stylife'       => 12,
		'buyma'       => 13,
    ),
    'hosts'        => array(
        'yshop'         => 'store.shopping.yahoo.co.jp',
        'zozo'          => 'zozo.jp',
        'amazon'        => 'amazon.co.jp',
        'felissimo'     => array('www.felissimo.co.jp', 'plus.felissimo.co.jp'),
        'locondo'       => 'www.locondo.jp',
        'fashionwalker' => array('fashionwalker.com', 's.fashionwalker.com'),
        'dinos'         => 'www.dinos.co.jp',
        'nissen'        => 'www.nissen.co.jp',
        'bellemaison'   => array('www.bellemaison.jp','item.bellemaison.jp'),
        'magaseek'      => array('www.magaseek.com', 's.magaseek.com'),
        'stylife'       => 'www.stylife.co.jp',
		'buyma'       => 'www.buyma.com',
    ),
    'urls'         => array(
        'yshop'         => 'http://store.shopping.yahoo.co.jp/',
        'zozo'          => 'http://zozo.jp/',
        'amazon'        => 'http://www.amazon.co.jp/',
        'felissimo'     => 'http://www.felissimo.co.jp/',
        'locondo'       => 'http://www.locondo.jp/',
        'fashionwalker' => 'http://fashionwalker.com/',
        'dinos'         => 'http://www.dinos.co.jp/',
        'nissen'        => 'http://www.nissen.co.jp/',
        'bellemaison'   => 'http://www.bellemaison.jp/',
        'magaseek'      => 'http://www.magaseek.com/',
        'stylife'       => 'http://www.stylife.co.jp/',
        'buyma'       => 'http://www.buyma.com/',
    ),
    'name'         => array(
        'yshop'         => 'Yahoo!ショッピング',
        'zozo'          => 'ZOZOTOWN',
        'amazon'        => 'Amazon.co.jp',
        'felissimo'     => 'FELISSIMO',
        'locondo'       => 'LOCONDO.jp',
        'fashionwalker' => 'FASHIONWALKER',
        'dinos'         => 'dinos',
        'nissen'        => 'NISSEN',
        'bellemaison'   => 'BELLEMAISON',
        'magaseek'      => 'MAGASEEK',
        'stylife'       => 'STYLIFE',
		'buyma' => 'BUYMA',
    ),
    'exe_wait_time'      => array(
        'yshop'         => 1000000,
        'zozo'          => 1000000,
        'amazon'        => 1000000,
        'felissimo'     => 1000000,
        'locondo'       => 1000000,
        'fashionwalker' => 1000000,
        'dinos'         => 1000000,
        'nissen'        => 1000000,
        'bellemaison'   => 1000000,
        'magaseek'      => 1000000,
        'stylife'       => 1000000,
        'buyma'       => 1000000,
    ),
    'affili'      => array(
        'yshop'         => 'http://ck.jp.ap.valuecommerce.com/servlet/referral?sid=2015148&pid=882802192&vc_url=',
    ),
    'tax' => 1.08,
);
